import type { Tab, TabArtwork } from './types'

const baseTabs: Tab[] = [
  {
    id: 'stairway',
    title: 'Stairway to Heaven',
    artist: 'Led Zeppelin',
    genre: 'Rock',
    tabType: 'Rhythm',
    meta: 'Гитара Ψ Standard E',
    difficulty: 'Средняя',
    rating: '4.9',
    views: '2.1M',
    badge: 'LED\nZEPPELIN',
    artwork: 'mist',
    featured: true,
  },
  {
    id: 'nothing',
    title: 'Nothing Else Matters',
    artist: 'Metallica',
    genre: 'Metal',
    tabType: 'Lead',
    meta: 'Гитара Ψ Standard E',
    difficulty: 'Средняя',
    rating: '4.8',
    views: '1.8M',
    badge: 'angle',
    artwork: 'dark',
    featured: true,
  },
  {
    id: 'sandman',
    title: 'Enter Sandman',
    artist: 'Metallica',
    genre: 'Metal',
    tabType: 'Rhythm',
    meta: 'Гитара Ψ Drop D',
    difficulty: 'Средняя',
    rating: '4.8',
    views: '1.6M',
    badge: 'slash',
    artwork: 'dark',
    featured: true,
  },
  {
    id: 'sweet-child',
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    genre: 'Rock',
    tabType: 'Rhythm',
    meta: 'Гитара Ψ Standard E',
    difficulty: 'Средняя',
    rating: '4.7',
    views: '1.5M',
    badge: 'circle',
    artwork: 'warm',
    featured: false,
  },
  {
    id: 'smells',
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    genre: 'Alternative',
    tabType: 'Acoustic',
    meta: 'Гитара Ψ Standard E',
    difficulty: 'Средняя',
    rating: '4.7',
    views: '1.4M',
    badge: 'mark',
    artwork: 'wine',
    featured: false,
  },
]

type ExtraTab = [
  title: string,
  artist: string,
  genre: string,
  rating: string,
  views: string,
  artwork: TabArtwork,
  badge: string,
  featured: boolean,
]

const extraTabs: ExtraTab[] = [
  ['Back in Black', 'AC/DC', 'Rock', '4.8', '1.3M', 'dark', 'angle', true],
  ['Hotel California', 'Eagles', 'Rock', '4.9', '1.2M', 'mist', 'LED\nTAB', false],
  ['Californication', 'Red Hot Chili Peppers', 'Alternative', '4.6', '980K', 'warm', 'circle', false],
  ['Blackbird', 'The Beatles', 'Acoustic', '4.7', '910K', 'dark', 'slash', false],
  ['Come As You Are', 'Nirvana', 'Alternative', '4.6', '880K', 'wine', 'mark', false],
  ['Wish You Were Here', 'Pink Floyd', 'Rock', '4.9', '850K', 'mist', 'PF', true],
  ['Seven Nation Army', 'The White Stripes', 'Rock', '4.5', '820K', 'dark', 'angle', false],
  ['Wonderwall', 'Oasis', 'Rock', '4.4', '790K', 'warm', 'circle', false],
  ['Creep', 'Radiohead', 'Alternative', '4.6', '760K', 'wine', 'mark', false],
  ['Knockin on Heaven’s Door', 'Bob Dylan', 'Rock', '4.5', '740K', 'mist', 'BD', false],
  ['Smoke on the Water', 'Deep Purple', 'Rock', '4.7', '710K', 'dark', 'slash', false],
  ['Zombie', 'The Cranberries', 'Alternative', '4.5', '690K', 'wine', 'mark', false],
  ['Sultans of Swing', 'Dire Straits', 'Rock', '4.8', '650K', 'mist', 'DS', true],
  ['Highway to Hell', 'AC/DC', 'Rock', '4.7', '630K', 'warm', 'circle', false],
  ['The Unforgiven', 'Metallica', 'Metal', '4.6', '610K', 'dark', 'angle', false],
]

export const tabs: Tab[] = [
  ...baseTabs,
  ...extraTabs.map(([title, artist, genre, rating, views, artwork, badge, featured], index) => ({
    id: `extra-${index + 1}`,
    title,
    artist,
    genre,
    tabType: index % 3 === 0 ? 'Lead' : 'Rhythm',
    meta: index % 3 === 0 ? 'Гитара Ψ Drop D' : 'Гитара Ψ Standard E',
    difficulty: index % 4 === 0 ? 'Легкая' : 'Средняя',
    rating,
    views,
    artwork,
    badge,
    featured,
  })),
]
